-- Generated by YourERD (2026-07-07)
-- Target: MySQL 8.x

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `Entity1` (
  `id` INT NOT NULL,
  `emp_type` VARCHAR(30) NOT NULL COMMENT 'emp_type 구분자',
  `column` VARCHAR(255) NULL COMMENT 'FULL_TIME',
  `column_PART_TIME` VARCHAR(255) NULL COMMENT 'PART_TIME',
  PRIMARY KEY (`id`),
  CHECK (`emp_type` IN ('FULL_TIME', 'PART_TIME')),
  CHECK (
    (`emp_type` = 'FULL_TIME' AND `column_PART_TIME` IS NULL) OR
    (`emp_type` = 'PART_TIME' AND `column` IS NULL)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
