-- Generated by YourERD (2026-07-07)
-- Target: MySQL 8.x

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `Entity1` (
  `pid` INT NOT NULL,
  PRIMARY KEY (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Entity2` (
  `vid` INT NOT NULL,
  `vehicle_type` VARCHAR(30) NULL COMMENT 'vehicle_type 구분자',
  `pid` INT NULL COMMENT 'Car',
  PRIMARY KEY (`vid`),
  CHECK (`vehicle_type` IN ('Car', 'Truck')),
  CHECK (
    (`vehicle_type` = 'Car') OR
    (`vehicle_type` = 'Truck' AND `pid` IS NULL) OR
    (`vehicle_type` IS NULL AND `pid` IS NULL)
  ),
  CONSTRAINT `fk_Entity2_Entity1` FOREIGN KEY (`pid`) REFERENCES `Entity1` (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Entity3` (
  `id` INT NOT NULL,
  `vid` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Entity3_Entity2` FOREIGN KEY (`vid`) REFERENCES `Entity2` (`vid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;
