// 다국어(한국어/영어) 지원 검증
//  - 기본 로케일 ko, 토글로 en 전환, 새로고침 후 영속
//  - 데이터 기본값(Entity1 등)은 로케일과 무관해야 함 (저장 데이터 불변식)
//  - 생성 텍스트(다이어그램 이름 프리필·SQL 주석)는 생성 시점 로케일을 따름
//  - 영문 가이드 페이지가 실제로 서빙됨 (SPA fallback으로 앱이 뜨면 실패)
import { chromium } from 'playwright';

const BASE = process.env.BASE_URL ?? 'http://localhost:5173';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 950 } });

let pass = 0, fail = 0;
const check = (name, ok, extra = '') => {
  if (ok) { pass++; console.log(`  PASS  ${name}`); }
  else { fail++; console.log(`  FAIL  ${name}${extra ? ' — ' + extra : ''}`); }
};

const html = () => page.evaluate(() => document.documentElement.lang);
const toggle = () => page.click('[data-testid="locale-toggle"]');
// 앞 단계가 남긴 상태에 의존하지 않도록, 목표 로케일이 될 때까지만 토글한다
const setLocale = async (target) => {
  if ((await html()) !== target) { await toggle(); await page.waitForTimeout(200); }
};

try {
  // ───── 1. 기본은 한국어 ─────
  await page.goto(BASE, { waitUntil: 'networkidle' });
  await page.waitForSelector('[data-testid="locale-toggle"]');
  check('기본 진입 시 lang="ko"', (await html()) === 'ko', await html());
  check('토글 배지가 KO', (await page.textContent('[data-testid="locale-toggle"]')).includes('KO'));
  check('사이드바가 한국어', await page.locator('text=아직 엔티티가 없습니다').isVisible());

  // ───── 2. 영어로 전환 ─────
  await toggle();
  await page.waitForTimeout(200);
  check('전환 후 lang="en"', (await html()) === 'en', await html());
  check('토글 배지가 EN', (await page.textContent('[data-testid="locale-toggle"]')).includes('EN'));
  check('사이드바가 영어', await page.locator('text=No entities yet').isVisible());
  check('한국어 문구 사라짐', !(await page.locator('text=아직 엔티티가 없습니다').isVisible()));

  // ───── 3. 새로고침 후 영속 ─────
  await page.reload({ waitUntil: 'networkidle' });
  await page.waitForSelector('[data-testid="locale-toggle"]');
  check('새로고침 후에도 영어 유지', (await html()) === 'en', await html());
  const stored = await page.evaluate(() => localStorage.getItem('erd-locale'));
  check('localStorage erd-locale 저장됨', !!stored && stored.includes('en'), String(stored));

  // ───── 4. 데이터 기본값은 로케일 무관 ─────
  await page.click('button:has-text("Add Entity")');
  await page.waitForSelector('.react-flow__node');
  const nodeText = await page.textContent('.react-flow__node');
  check('영어 모드에서도 엔티티 기본명은 Entity1', nodeText.includes('Entity1'), nodeText.slice(0, 60));
  check('영어 모드에서도 기본 PK 컬럼명은 id', nodeText.includes('id'));

  // ───── 5. 편집 모달이 영어 ─────
  await page.locator('.react-flow__node').first().hover();
  await page.click('[data-testid="entity-info-icon"]');
  await page.waitForSelector('[data-testid="entity-editor-modal"]');
  const modal = page.locator('[data-testid="entity-editor-modal"]');
  check('편집 모달 라벨이 영어(Table Name)', (await modal.textContent()).includes('Table Name'));
  check('편집 모달에 한글 라벨 없음(물리명)', !(await modal.textContent()).includes('물리명'));
  await page.keyboard.press('Escape');

  // ───── 6. 생성 텍스트는 로케일을 따름 (SQL 헤더) ─────
  const dl = page.waitForEvent('download');
  await page.click('[title="Export SQL (MySQL)"]');
  const sql = await (await dl).path().then(p => import('node:fs').then(fs => fs.readFileSync(p, 'utf-8')));
  check('영어 모드 SQL 헤더가 영문', sql.includes('-- Generated by YourERD'), sql.split('\n')[0]);
  check('SQL 방언 표기는 로케일 무관', sql.includes('-- Target: MySQL 8.x'));

  // ───── 7. 한국어로 되돌리면 SQL 헤더도 한국어 ─────
  await toggle();
  await page.waitForTimeout(200);
  const dl2 = page.waitForEvent('download');
  await page.click('[title="SQL 내보내기 (MySQL)"]');
  const sql2 = await (await dl2).path().then(p => import('node:fs').then(fs => fs.readFileSync(p, 'utf-8')));
  check('한국어 모드 SQL 헤더가 한국어', sql2.includes('YourERD로 생성됨'), sql2.split('\n')[0]);
  check('내보낸 DDL의 테이블명은 로케일 무관', sql2.includes('`Entity1`'));

  // ───── 8. 삭제 확인 다이얼로그 (공통 헬퍼 경유) ─────
  await page.click('.react-flow__node');
  await page.keyboard.press('Delete');
  await page.waitForSelector('[data-testid="app-dialog"]');
  check('한국어 모드 삭제 다이얼로그', (await page.textContent('[data-testid="app-dialog"]')).includes('엔티티 삭제'));
  await page.keyboard.press('Escape');
  await toggle();
  await page.waitForTimeout(200);
  await page.click('.react-flow__node');
  await page.keyboard.press('Delete');
  await page.waitForSelector('[data-testid="app-dialog"]');
  check('영어 모드 삭제 다이얼로그', (await page.textContent('[data-testid="app-dialog"]')).includes('Delete entity'));
  await page.keyboard.press('Escape');

  // ───── 9. 가이드 페이지가 로케일별로 분기되는지 ─────
  //  영문 경로 파일이 없으면 404가 아니라 SPA fallback으로 앱이 조용히 뜨므로, 실제 내용까지 확인한다.
  await setLocale('en');
  const enHref = await page.getAttribute('a[href$="/manual.html"]', 'href');
  check('영어 모드 Docs 링크가 /en/manual.html', enHref === '/en/manual.html', String(enHref));
  await setLocale('ko');
  const koHref = await page.getAttribute('a[href$="/manual.html"]', 'href');
  check('한국어 모드 Docs 링크가 /manual.html', koHref === '/manual.html', String(koHref));

  for (const [path, expect] of [
    ['/en/manual.html', 'User Manual'],
    ['/en/mcp-guide.html', 'MCP Setup Guide'],
    ['/en/prompt-guide.html', 'Claude Prompt Guide'],
  ]) {
    const res = await page.goto(BASE + path, { waitUntil: 'domcontentloaded' });
    const title = await page.title();
    const lang = await html();
    check(`${path} 서빙됨 (SPA fallback 아님)`,
      res.status() === 200 && title.includes(expect) && lang === 'en',
      `status=${res.status()} title=${title} lang=${lang}`);
  }
  // 한국어 원본도 그대로 살아 있어야 함
  await page.goto(BASE + '/manual.html', { waitUntil: 'domcontentloaded' });
  check('/manual.html 한국어 원본 유지', (await page.title()).includes('사용자 매뉴얼'), await page.title());
  check('가이드 공통 CSS 적용됨',
    (await page.evaluate(() => getComputedStyle(document.body).backgroundColor)) === 'rgb(19, 19, 19)');

  await page.goto(BASE, { waitUntil: 'networkidle' });
  await page.waitForSelector('[data-testid="locale-toggle"]');
  await setLocale('en');
  await page.screenshot({ path: 'ss_i18n_en.png' });
  await setLocale('ko');
  await page.screenshot({ path: 'ss_i18n_ko.png' });
} catch (e) {
  fail++;
  console.log('  FAIL  예외:', e.message);
  await page.screenshot({ path: 'ss_i18n_error.png' }).catch(() => {});
}

console.log(`\n${fail === 0 ? 'ALL PASS' : 'FAILED'} — ${pass} passed, ${fail} failed`);
await browser.close();
process.exit(fail === 0 ? 0 : 1);
