import { Entity, Column } from '../types/erd';

// MySQL DDL 생성 — 엔티티/컬럼(FK 메타 포함)을 CREATE TABLE 스크립트로 변환
// - 타입 매핑: UUID→CHAR(36), VARCHAR/CHAR/DECIMAL/FLOAT는 size 반영, 나머지는 그대로
// - 논리명 → COMMENT, 엔티티 설명은 테이블 COMMENT에 병기
// - FK: refEntityId별로 묶어 복합 FOREIGN KEY 제약 생성 (참조 대상이 없으면 일반 컬럼으로만 출력)
// - 테이블 순서: 부모 우선 토폴로지 정렬, 순환 대비 FOREIGN_KEY_CHECKS 비활성 래핑

const q = (ident: string) => `\`${ident.replace(/`/g, '``')}\``;
const comment = (text: string) => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;

function mysqlType(col: Column): string {
  const size = col.size.trim();
  switch (col.type) {
    case 'UUID': return 'CHAR(36)'; // MySQL은 UUID 타입이 없음
    case 'VARCHAR': return `VARCHAR(${size || '255'})`;
    case 'CHAR': return `CHAR(${size || '1'})`;
    case 'DECIMAL': return `DECIMAL(${size || '10,2'})`;
    case 'FLOAT': return size ? `FLOAT(${size})` : 'FLOAT';
    default: return col.type;
  }
}

function columnLine(col: Column): string {
  const parts = [q(col.name), mysqlType(col)];
  if (col.isNN || col.isPK) parts.push('NOT NULL');
  else parts.push('NULL');
  if (col.isUnique && !col.isPK) parts.push('UNIQUE');
  if (col.logicalName?.trim()) parts.push(`COMMENT ${comment(col.logicalName.trim())}`);
  return parts.join(' ');
}

// 부모 우선 정렬 (Kahn) — FK 참조 기준, 순환은 원래 순서대로 뒤에 붙임
function sortParentsFirst(entities: Entity[]): Entity[] {
  const ids = new Set(entities.map(e => e.id));
  const inDeg = new Map(entities.map(e => [e.id, 0]));
  const children = new Map<string, string[]>(entities.map(e => [e.id, []]));
  for (const e of entities) {
    const parents = new Set(
      e.columns.filter(c => c.isFK && c.refEntityId && ids.has(c.refEntityId) && c.refEntityId !== e.id)
        .map(c => c.refEntityId!)
    );
    for (const p of parents) {
      children.get(p)!.push(e.id);
      inDeg.set(e.id, inDeg.get(e.id)! + 1);
    }
  }
  const sorted: Entity[] = [];
  const queue = entities.filter(e => inDeg.get(e.id) === 0);
  const byId = new Map(entities.map(e => [e.id, e]));
  while (queue.length) {
    const e = queue.shift()!;
    sorted.push(e);
    for (const cid of children.get(e.id)!) {
      inDeg.set(cid, inDeg.get(cid)! - 1);
      if (inDeg.get(cid) === 0) queue.push(byId.get(cid)!);
    }
  }
  // 순환 참여 테이블 — FOREIGN_KEY_CHECKS=0 래핑으로 실행은 가능
  for (const e of entities) if (!sorted.includes(e)) sorted.push(e);
  return sorted;
}

export function generateMySQLDDL(entities: Entity[]): string {
  const byId = new Map(entities.map(e => [e.id, e]));
  const usedFkNames = new Set<string>();
  const today = new Date().toISOString().slice(0, 10);

  const tables = sortParentsFirst(entities).map(entity => {
    const lines = entity.columns.map(c => `  ${columnLine(c)}`);

    const pkCols = entity.columns.filter(c => c.isPK);
    if (pkCols.length > 0) {
      lines.push(`  PRIMARY KEY (${pkCols.map(c => q(c.name)).join(', ')})`);
    }

    // FK 제약 — 같은 부모를 참조하는 컬럼끼리 복합 제약으로 묶음
    const fkGroups = new Map<string, Column[]>();
    for (const c of entity.columns) {
      if (!c.isFK || !c.refEntityId || !byId.has(c.refEntityId)) continue;
      const parent = byId.get(c.refEntityId)!;
      if (!parent.columns.some(pc => pc.id === c.refColumnId)) continue; // 참조 컬럼 소실 시 제약 생략
      const group = fkGroups.get(c.refEntityId) ?? [];
      group.push(c);
      fkGroups.set(c.refEntityId, group);
    }
    for (const [refId, cols] of fkGroups) {
      const parent = byId.get(refId)!;
      let name = `fk_${entity.name}_${parent.name}`;
      for (let i = 2; usedFkNames.has(name); i++) name = `fk_${entity.name}_${parent.name}_${i}`;
      usedFkNames.add(name);
      const refCols = cols.map(c => parent.columns.find(pc => pc.id === c.refColumnId)!);
      lines.push(
        `  CONSTRAINT ${q(name)} FOREIGN KEY (${cols.map(c => q(c.name)).join(', ')})` +
        ` REFERENCES ${q(parent.name)} (${refCols.map(c => q(c.name)).join(', ')})`
      );
    }

    const tableComment = [entity.logicalName?.trim(), entity.description?.trim()]
      .filter(Boolean).join(' — ');
    const options = ['ENGINE=InnoDB', 'DEFAULT CHARSET=utf8mb4'];
    if (tableComment) options.push(`COMMENT=${comment(tableComment)}`);

    return `CREATE TABLE ${q(entity.name)} (\n${lines.join(',\n')}\n) ${options.join(' ')};`;
  });

  return [
    `-- Generated by DataModeler Pro (${today})`,
    '-- Target: MySQL 8.x',
    '',
    'SET FOREIGN_KEY_CHECKS = 0;',
    '',
    tables.join('\n\n'),
    '',
    'SET FOREIGN_KEY_CHECKS = 1;',
    '',
  ].join('\n');
}

// .sql 파일 다운로드
export function exportDiagramSql(entities: Entity[]): void {
  if (entities.length === 0) return;
  const sql = generateMySQLDDL(entities);
  const blob = new Blob([sql], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `erd-${new Date().toISOString().slice(0, 10)}.sql`;
  a.click();
  URL.revokeObjectURL(url);
}
